### ISSUE TITLE
README description of timeclock.el is wrong

### ISSUE THREAD

**Issue by jwiegley** [contrapunctus-1/chronometrist#1]
timeclock.el uses a line-based format, not a s-expr one.

**Comment by contrapunctus-1** [comment]
@jwiegley Honored to hear from you 😀 Sorry it wasn't very clear, I've pushed a change, hope it's clearer now.

https://github.com/contrapunctus-1/chronometrist/commit/875400f61cd4c1fff1536b2bbc68f8e35d278cd0

**Comment by jwiegley** [comment]
Thank you!

**Comment by jwiegley** [comment]
Also, please accept my apologies for the abruptness of this ticket. I didn't mean it come across as critical, I really like seeing more work in this area, so thank you for your efforts.
